{% set version = "4.12.0" %}

package:
  name: asphalt
  version: {{ version }}

source:
  url: https://github.com/asphalt-framework/asphalt/archive/refs/tags/{{ version }}.tar.gz
  sha256: db0fe5eca288e68b7b7159e8785f8601cbd7bc1a51ed8a5baa668700b252a34a

build:
  noarch: python
  number: 2
  entry_points:
    - asphalt = asphalt.core.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.7
    - importlib_metadata >=4.4
    - typing_extensions
    - ruamel.yaml >=0.15
    - async_generator >=1.4,<2
    - asyncio_extras >=1.3,<2
    - async-timeout >=2.0
    - click >=6.6

test:
  imports:
    - asphalt
  commands:
    - asphalt --help

about:
  home: https://github.com/asphalt-framework/asphalt
  doc_url: https://asphalt.readthedocs.org
  dev_url: https://github.com/asphalt-framework/asphalt
  license: Apache-2.0
  license_file: LICENSE
  summary: An asyncio based microframework for network oriented applications

extra:
  recipe-maintainers:
    - davidbrochart
