{% set version = "4.11.1" %}

package:
  name: asphalt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/asphalt/asphalt-{{ version }}.tar.gz
  sha256: 2db407956cdc8e9b71619f68b102f5e6affa4e3caf42e02927c03b81d49db3b6

build:
  noarch: python
  number: 0
  entry_points:
    - asphalt = asphalt.core.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.7
    - importlib_metadata >=4.4
    - typing_extensions
    - ruamel.yaml >=0.15
    - typeguard >=2.0,<3
    - async_generator >=1.4,<2
    - asyncio_extras >=1.3,<2
    - async-timeout >=2.0
    - click >=6.6

test:
  imports:
    - asphalt
  commands:
    - asphalt --help

about:
  home: https://github.com/asphalt-framework/asphalt
  doc_url: https://asphalt.readthedocs.org
  dev_url: https://github.com/asphalt-framework/asphalt
  license: Apache-2.0
  license_file: LICENSE
  summary: An asyncio based microframework for network oriented applications

extra:
  recipe-maintainers:
    - davidbrochart
